### ISSUE TITLE
Original ImportError was: ModuleNotFoundError("No module named 'amp_C')

### ISSUE THREAD

**Issue by misslibra** [NVIDIA/apex#573]
my env is CUDA 10.1, and pytorch 1.3,GPU v100,python 3.6,
and I get error:

Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    lr_scheduler = config_lr_scheduler(args, optimizer)
  File "/home/perception/Documents/apex-master/geely_yolo3D/utils/utils.py", line 553, in config_lr_scheduler
    return torch.optim.lr_scheduler.StepLR(optimizer, args.lr_decay_epoch, args.gamma)
  File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 208, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch)
  File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 58, in __init__
    self.optimizer.step = with_counter(self.optimizer.step)
  File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 40, in with_counter
    instance_ref = weakref.ref(method.__self__)
AttributeError: 'function' object has no attribute '__self__'

My code run well in env : CUDA 9,pytorch 1.2,GPU P4000,python 3.6

Please help me with this issue.

**Comment by mcarilli** [comment]
Should by fixed by https://github.com/NVIDIA/apex/pull/553.  Try puling the latest master and reinstalling:
```
apex $ git pull
apex $ pip uninstall apex # repeat until you're sure it's gone
apex $ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by misslibra** [comment]
Thanks for your reply !
I download code zip yesterday ,which should be the latest version.
and I have fixed the problem by pip install using pip in  conda--bin install of pip default .

**Comment by soodeh-nilforoushan** [comment]
Hi, I did not understand how you fix this error? I was stuck for two days for this error, if someone can help me, I would be happy!

**Comment by CRaimondo** [comment]
Also getting this error and not sure how you fixed @misslibra

**Comment by JoshLuxton** [comment]
Phew. this was hard to get working.

To the couple new commenters from the past week - this won't work in an environment with cuda-tookit-11+ you will need cuda-toolkit-10-2.

don't touch your cuda drivers just follow the instructions here: https://www.mathworks.com/matlabcentral/answers/687133-how-to-install-supported-cuda-toolkit-10-2-on-ubuntu-20-04-lts-linux

when it references: https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork

follow all steps from the archive EXCEPT when it says to install cuda (this will overwrite your drivers and cause incompatibility). Instead, install cuda-toolkit-10-2 

this should update nvcc -V to reference 10.2, but if it doesnt check /usr/local/cuda:
```
ls -la /usr/local/cuda*
```
often multiple toolkits can live there.. and often you will see a symlink from /usrl/local/cuda to whichever version of cuda nvcc will reference for compile. 

after that is setup and you follow the instructions for setting alternative gcc version you can proceed with the install listed in mcarills comment from Oct 31, 2019

**Comment by alexqdh** [comment]
> 

After install apex, it still occurs error `ImportError: libc10.so`. It should import torch before amp_C, just like this:

```
import torch
import amp_C
```

Install torch-1.12.1 gpu version:

```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
```

**Comment by liaochuanlin** [comment]
ERROR: Could not build wheels for apex, which is required to install pyproject.toml-based projects

**Comment by ming-afk** [comment]
> ERROR: Could not build wheels for apex, which is required to install pyproject.toml-based projects

maybe try this: 
https://github.com/NVIDIA/apex/issues/1594#issuecomment-1696916176

**Comment by hayatkhan8660-maker** [comment]
> my env is CUDA 10.1, and pytorch 1.3,GPU v100,python 3.6, and I get error:
> 
> Warning: multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback. Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",) Traceback (most recent call last): File "train.py", line 104, in lr_scheduler = config_lr_scheduler(args, optimizer) File "/home/perception/Documents/apex-master/geely_yolo3D/utils/utils.py", line 553, in config_lr_scheduler return torch.optim.lr_scheduler.StepLR(optimizer, args.lr_decay_epoch, args.gamma) File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 208, in **init** super(StepLR, self).**init**(optimizer, last_epoch) File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 58, in **init** self.optimizer.step = with_counter(self.optimizer.step) File "/home/perception/anaconda3/envs/new/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 40, in with_counter instance_ref = weakref.ref(method.**self**) AttributeError: 'function' object has no attribute '**self**'
> 
> My code run well in env : CUDA 9,pytorch 1.2,GPU P4000,python 3.6
> 
> Please help me with this issue.

Have you solved this issue?

I am having the same issue..
